USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'DB_PRUEBA_TECNICA')
BEGIN
    ALTER DATABASE DB_PRUEBA_TECNICA SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DB_PRUEBA_TECNICA;
END
GO

CREATE DATABASE DB_PRUEBA_TECNICA;
GO

USE DB_PRUEBA_TECNICA;
GO

-- ==========================================
-- TABLA ROL
-- ==========================================
CREATE TABLE ROL (
    ID_ROL INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NULL,
    ACTIVO BIT NOT NULL DEFAULT 1
);
GO

-- ==========================================
-- TABLA USUARIO
-- ==========================================
CREATE TABLE USUARIO (
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    ID_ROL INT NOT NULL,
    NOMBRE_USUARIO VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENA_HASH VARBINARY(512) NOT NULL,
    CORREO VARCHAR(150) NOT NULL,
    ACTIVO BIT NOT NULL DEFAULT 1,
    FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
);
GO

-- ==========================================
-- TABLA PRODUCTO
-- ==========================================
CREATE TABLE PRODUCTO (
    ID_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
    CODIGO VARCHAR(50) NOT NULL UNIQUE,
    NOMBRE VARCHAR(150) NOT NULL,
    DESCRIPCION VARCHAR(500) NULL,
    PRECIO DECIMAL(10,2) NOT NULL CHECK (PRECIO >= 0),
    STOCK INT NOT NULL CHECK (STOCK >= 0),
    ACTIVO BIT NOT NULL DEFAULT 1,
    FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_ACTUALIZACION DATETIME NULL
);
GO

-- ==========================================
-- TABLA PEDIDO
-- ==========================================
CREATE TABLE PEDIDO (
    ID_PEDIDO INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ESTADO VARCHAR(20) NOT NULL CHECK (ESTADO IN ('PENDIENTE', 'CONFIRMADO', 'RECHAZADO', 'CANCELADO')),
    TOTAL DECIMAL(12,2) NOT NULL DEFAULT 0,
    FECHA_PEDIDO DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_ACTUALIZACION DATETIME NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
GO

-- ==========================================
-- TABLA DETALLE_PEDIDO
-- ==========================================
CREATE TABLE DETALLE_PEDIDO (
    ID_DETALLE_PEDIDO INT IDENTITY(1,1) PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL CHECK (CANTIDAD > 0),
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL AS (CANTIDAD * PRECIO_UNITARIO) PERSISTED,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);
GO

-- ==========================================
-- TABLA BITACORA_INVENTARIO
-- ==========================================
CREATE TABLE BITACORA_INVENTARIO (
    ID_BITACORA INT IDENTITY(1,1) PRIMARY KEY,
    ID_PRODUCTO INT NOT NULL,
    ID_USUARIO INT NULL,
    ACCION VARCHAR(50) NOT NULL,
    CANTIDAD INT NOT NULL,
    FECHA DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
GO
