USE DB_PRUEBA_TECNICA;
GO

IF OBJECT_ID('SP_GET_ALL_PRODUCTS', 'P') IS NOT NULL
    DROP PROCEDURE SP_GET_ALL_PRODUCTS;
GO

CREATE PROCEDURE SP_GET_ALL_PRODUCTS
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        ID_PRODUCTO,
        CODIGO,
        NOMBRE,
        DESCRIPCION,
        PRECIO,
        STOCK,
        ACTIVO,
        FECHA_CREACION,
        FECHA_ACTUALIZACION
    FROM PRODUCTO
    WHERE ACTIVO = 1
    ORDER BY NOMBRE;
END
GO
